# Generated by Django 5.0.6 on 2024-06-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='productc',
            new_name='product',
        ),
    ]
